<a href="https://colab.research.google.com/github/Mansha125/Internpy/blob/Beginning/rock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


hm=np.array([100,200,300,400])
pr=np.array([500,1000,500,1000])
print(hm)
print(pr,"\n")

hm_train, hm_test, pr_train, pr_test = train_test_split(hm, pr, test_size=0.5, random_state=42)

print(hm_train)
print(hm_test,"\n")

print(pr_train)
print(pr_test)


r=LinearRegression().fit(hm_train.reshape(-1,1),pr_train.reshape(-1,1))
print(r.score(pr_test.reshape(-1,1),hm_test.reshape(-1,1)))
r.predict(hm_test.reshape(-1,1))


[100 200 300 400]
[ 500 1000  500 1000] 

[100 300]
[200 400] 

[500 500]
[1000 1000]
-4.0


array([[500.],
       [500.]])

In [ ]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression



home=np.array([50,100,200,300,400,600,700])
price=np.array([25,50,100,150,200,300,350])
print(home)
print(price,"\n")

home_train, home_test, price_train, price_test = train_test_split(home, price, test_size=0.1, random_state=32,shuffle=True)

print(home_train)
print(home_test,"\n")

print(price_train)
print(price_test)


print(price_test)
r=LinearRegression().fit(home_train.reshape(-1,1),price_train.reshape(-1,1))
print(r.score(home_test.reshape(-1,1),price_test.reshape(-1,1)))
r.predict(home_test.reshape(-1,1))


[ 50 100 200 300 400 600 700]
[ 25  50 100 150 200 300 350] 

[100  50 200 400 600 300]
[700] 

[ 50  25 100 200 300 150]
[350]
[350]
nan


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:918: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


array([[350.]])

In [8]:
for i in range
  print("Yes or No : ")
  a=input()

while not(a=="No"):

  if (a=="Yes"):
    print("Enter name:")
    name=input()
    print(name)
  else:
    print("Exit")

Yes or No : 
Enter name:
mansha
Enter name:
mansha
Enter name:

Enter name:


KeyboardInterrupt: Interrupted by user

In [14]:
while True:
    print("Yes or No : ")
    a = input()
    if a == "Yes":
        print("Enter name:")
        name = input()
        names = []
        names.append(name)
    elif a == "No":
        print("Exit")
        break
print(names)



Yes or No : 
Yes
Enter name:
Vishal
Yes or No : 


KeyboardInterrupt: Interrupted by user

In [43]:
names = []
while True:
    user_input = input("Please enter name (or type 'stop' to end): ")
    length=len(user_input)
    if length==0:
        break
    names.append(user_input)
print(names)




Please enter name (or type 'stop' to end): v
Please enter name (or type 'stop' to end): s
Please enter name (or type 'stop' to end): a
Please enter name (or type 'stop' to end): 
['v', 's', 'a']


In [38]:
import random


mines = input("Enter a choice (rock, paper, scissors): ")
mine=mines.casefold()

possible_outcomes = ["rock", "paper", "scissors"]


machine = random.choice(possible_outcomes)
print(f"\nYou chose {mine}, computer chose {machine}.\n")

if mine == machine:
    print(f"Both players selected {mine}. It's a tie!")

elif mine == "rock":

    if machine == "scissors":
        print("Rock smashes scissors! You win!")

    else:
        print("Paper covers rock! You lose.")

elif mine == "paper":

    if machine == "rock":
        print("Paper covers rock! You win!")

    else:
        print("Scissors cuts paper! You lose.")

elif mine == "scissors":

    if machine == "paper":
        print("Scissors cuts paper! You win!")

    else:
        print("Rock smashes scissors! You lose.")


Enter a choice (rock, paper, scissors): ROCK

You chose rock, computer chose rock.

Both players selected rock. It's a tie!
